### ISSUE TITLE
Great tool! Do you mind to implement a drag to upload function with automatic conversion?

### ISSUE THREAD

**Issue by mtoensing** [oguzalpcakmak/xbox360-retitler#1]
Thanks! Just what I needed! It works! I converted many ISOs while xboxunity was down. So my GODs have not title. Could you implement a drag to upload function with automatic conversion? Or any other improvement to speed this process up if you had to to this for many GODs?

**Comment by oguzalpcakmak** [comment]
v2 update just released! thanks for the feedback! you can try it at: https://oguzalpcakmak.github.io/xbox360-retitler/
